"""runtime"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002_runtime"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.String(length=160), nullable=False),
        sa.Column("actor_id", sa.String(length=160), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "budget_counters",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("bucket", sa.String(length=160), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("day", "bucket"),
    )
    op.create_table(
        "login_states",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("browser_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("state_hash"),
    )
    op.create_table(
        "market_observations",
        sa.Column("observation_id", sa.String(length=160), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("record_id", sa.String(length=160), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("observation_id", "revision"),
    )
    op.create_table(
        "runtime_health",
        sa.Column("component", sa.String(length=160), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("component"),
    )
    op.create_table(
        "subjects",
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("identity_key", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("build_token", sa.String(length=64), nullable=True),
        sa.Column("build_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("subject_id"),
        sa.UniqueConstraint("identity_key"),
    )
    op.create_table(
        "users",
        sa.Column("actor_id", sa.String(length=160), nullable=False),
        sa.Column("recipient_id", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=160), nullable=False),
        sa.Column("provider_subject", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_test_recipient", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("actor_id"),
        sa.UniqueConstraint("provider", "provider_subject", name="uq_user_identity"),
        sa.UniqueConstraint("recipient_id"),
    )
    op.create_table(
        "feedback",
        sa.Column("feedback_id", sa.String(length=160), nullable=False),
        sa.Column("actor_id", sa.String(length=160), nullable=False),
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.actor_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_table(
        "quote_previews",
        sa.Column("preview_id", sa.String(length=160), nullable=False),
        sa.Column("actor_id", sa.String(length=160), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_records", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("import_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.actor_id"],
        ),
        sa.PrimaryKeyConstraint("preview_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=160), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.actor_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "subject_versions",
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("decision_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.subject_id"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "revision"),
    )
    op.create_table(
        "recipient_authorizations",
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.String(length=160), nullable=False),
        sa.Column("authorization_id", sa.String(length=160), nullable=False),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("reminders_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.recipient_id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "revision"],
            ["subject_versions.subject_id", "subject_versions.revision"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "revision", "recipient_id"),
        sa.UniqueConstraint("authorization_id"),
    )
    op.create_table(
        "subject_evidence",
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.String(length=160), nullable=False),
        sa.Column("record_revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id", "record_revision"],
            ["source_records.record_id", "source_records.revision"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "revision"],
            ["subject_versions.subject_id", "subject_versions.revision"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "revision", "record_id", "record_revision"),
    )
    op.create_table(
        "notification_intents",
        sa.Column("intent_id", sa.String(length=160), nullable=False),
        sa.Column("subject_id", sa.String(length=160), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id", "revision", "recipient_id"],
            [
                "recipient_authorizations.subject_id",
                "recipient_authorizations.revision",
                "recipient_authorizations.recipient_id",
            ],
        ),
        sa.PrimaryKeyConstraint("intent_id"),
        sa.UniqueConstraint(
            "subject_id",
            "revision",
            "recipient_id",
            "kind",
            "channel",
            name="uq_intent_business_key",
        ),
    )
    op.create_table(
        "deliveries",
        sa.Column("delivery_id", sa.String(length=160), nullable=False),
        sa.Column("intent_id", sa.String(length=160), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("platform_message_id", sa.String(length=256), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["notification_intents.intent_id"],
        ),
        sa.PrimaryKeyConstraint("delivery_id"),
        sa.UniqueConstraint("intent_id"),
    )
    op.create_table(
        "acknowledgements",
        sa.Column("ack_id", sa.String(length=160), nullable=False),
        sa.Column("delivery_id", sa.String(length=160), nullable=False),
        sa.Column("callback_id", sa.String(length=160), nullable=False),
        sa.Column("actor_id", sa.String(length=160), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.actor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.delivery_id"],
        ),
        sa.PrimaryKeyConstraint("ack_id"),
        sa.UniqueConstraint("callback_id"),
    )
    op.add_column(
        "source_records", sa.Column("attempt", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("source_records", sa.Column("lease_token", sa.String(length=64), nullable=True))
    op.add_column(
        "source_records", sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "source_records", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("source_records", sa.Column("error_code", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_records", "error_code")
    op.drop_column("source_records", "next_attempt_at")
    op.drop_column("source_records", "lease_until")
    op.drop_column("source_records", "lease_token")
    op.drop_column("source_records", "attempt")
    op.drop_table("acknowledgements")
    op.drop_table("deliveries")
    op.drop_table("notification_intents")
    op.drop_table("subject_evidence")
    op.drop_table("recipient_authorizations")
    op.drop_table("subject_versions")
    op.drop_table("sessions")
    op.drop_table("quote_previews")
    op.drop_table("feedback")
    op.drop_table("users")
    op.drop_table("subjects")
    op.drop_table("runtime_health")
    op.drop_table("market_observations")
    op.drop_table("login_states")
    op.drop_table("budget_counters")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
